version: "3.7"
services:
  app: 
    build:
      context: ./integration-themoviedb-api/
      dockerfile: Dockerfile
    image: integration-api
    container_name: integration-themoviedb-api
    restart: unless-stopped
    working_dir: /usr/app
    ports: 
      - "3333:3333"
    volumes:
      - ./usr/app
    networks:
      - integration

  db-develop:
    image: mysql:5.7
    container_name: integration-themoviedb-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: FavoriteMovies
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_USER: maiconparra
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports: 
      - "3306:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - integration

networks:
  integration:
    driver: bridge